# logging ??
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

# console ??
spring:
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# ?? ??
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port ??
  port: 8080
